// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Mon, 19 Oct 2015 08:23:10 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.18919.0")]
[assembly: AssemblyFileVersion("1.0.18919.823")]
