// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 15 Oct 2015 06:48:23 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.18915.0")]
[assembly: AssemblyFileVersion("1.0.18915.648")]
